name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: devopsifyme
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devopsifyme/containersterminal:${{ steps.gitversion.outputs.semVer }}

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: docker push devopsifyme/containersterminal:${{ steps.gitversion.outputs.semVer }}

    - name: Tag Docker Image as latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag devopsifyme/containersterminal:${{ steps.gitversion.outputs.semVer }} devopsifyme/containersterminal:latest 
        docker tag devopsifyme/containersterminal:${{ steps.gitversion.outputs.semVer }} devopsifyme/containersterminal:${{ steps.gitversion.outputs.major }} 
        docker tag devopsifyme/containersterminal:${{ steps.gitversion.outputs.semVer }} devopsifyme/containersterminal:${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }} 
        docker tag devopsifyme/containersterminal:${{ steps.gitversion.outputs.semVer }} devopsifyme/containersterminal:${{ steps.gitversion.outputs.majorMinorPatch }}
        docker push devopsifyme/containersterminal:latest
        docker push devopsifyme/containersterminal:${{ steps.gitversion.outputs.major }} 
        docker push devopsifyme/containersterminal:${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }} 
        docker push devopsifyme/containersterminal:${{ steps.gitversion.outputs.majorMinorPatch  }}

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: v${{ steps.gitversion.outputs.SemVer }}
        tag_name: v${{ steps.gitversion.outputs.SemVer }}

